### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by kael-shipman**
Hi there!

I was looking for a library like this and found yours and liked it, but I wanted a few minor changes. I figured it would be easier to just implement them and discuss them with you here in this PR than to write a bunch of issues and discuss them all individually.

Please grab a look and see what you think. If you like what you see, please incorporate the changes and issue a new release. If you like some but not all, feel free to discuss them with me or just cherry-pick the commits you want. If you don't like any of it, just lemme know and maybe I'll publish my own version of the library for my own use.

### Explanation of Changes

* **Commit 2b761cf:** When I ran `npm install` on the library, I got a warning that the crypto library had been deprecated because it had been fully incorporated natively into nodejs. Thinking about it now, I wonder if perhaps you wanted to use this on the front-end and so still needed the external `crypto` dependency. If that's the case, maybe we can make it an optional dependency?
* **Commit 49c0de2:** When I ran `npm install`, I noticed that package-lock.json showed up in the list of untracked files. I figured if you hadn't already added it to the library, it's because you didn't want it there, so I took the liberty of ignoring it.
* **Commit df2e988:** I thought it would be useful to be able to declare the type of the output of the decrypt function, so I added a type parameter.
* **Commit 80f773f:** Encrypting small strings like "123456789" resulted in 1000+ character encryptions, which I believed was a result of using a 256-character salt. To fix this for myself in a backward compatible way, I added an optional options hash as a final parameter, which includes `saltLength` and a few other parameters that may be of interest to other consumers of the library.
* **Commit 96a2e46:** Added an option to return a buffer, rather than string.

Please let me know what you think.

### CODE REVIEW

**Comment by kael-shipman** [comment]
@cavillo just wondering if you saw this or had any opinions about it. It would be great if you would release a version based on these changes. If not, though, I can release the new version under my personal github account. Please let me know what you prefer.

**Comment by kael-shipman** [comment]
Ok, assuming this is probably a dead thread. If I don't hear from you this week, I'm going to release my own fork of this project. Thanks for the starting point either way!

**Comment by kael-shipman** [comment]
Closing in favor of kael-shipman/encryptor-node#1

**Comment by cavillo** [comment]
@kael-shipman thank you for your contribution. I'm not sure how I missed all of this. I apologize for that.
I noticed you forked the repo and created a new npm package 👍.

**Review by cavillo — APPROVED** [review]

**Comment by kael-shipman** [comment]
Oh cool! Sorry you didn't get the messages before. I've found I often miss github messages for one reason or another. Hopefully an area they improve on....

Anyway, glad to see you liked the changes, and thanks for the lib!

**Pull request merged**
